### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-conferences#106]
I would like to have some help maintaining and overhauling this list. Is anyone interested? 

cc @brittanystoroz @Stephn-R.

**Comment by RichardLitt** [comment]
@brittanystoroz @joshsimmons checked again, and it looks like I already have you as maintainers! Are you interested in helping me overhaul and improve this list?

**Comment by lirantal** [comment]
Great. Definitely should keep this one up to date.
I'm wondering though if we want to separate it by years so that it's also easy to track past events?

**Comment by RichardLitt** [comment]
Makes sense to me. Let's do that. Alphabetization is a largely useless
schema for organizing unknown things.

**Comment by RichardLitt** [comment]
@lirantal If you'd be keen to helping out, PRs accepted. :) Happy to make you a maintainer after a couple of edits are merged.

**Comment by thejessleigh** [comment]
I'm definitely interested in helping out, but looking at the new format I'm not exactly sure how to make it work with some conferences. What should I include for the location for conferences that move, like PyCon or RubyConf? Or for conferences that have many recurring dates and locations like AlterConf?

**Comment by RichardLitt** [comment]
How about: `location: variable`? For conferences with recurring dates, use an array. We can change the format to make it easier. :)

**Comment by thejessleigh** [comment]
Sounds good. I love this list idea, but I think I'm just a little confused between the Awesome Conferences and the Past Conferences section. Should each year of a conference be treated as a distinct entity? Should we be proactive about moving conferences that have passed from the top to the Past Conferences section? I know I'm coming into this in the middle of a redesign, but from the docs it's a little difficult to tell what the intent is for the new format.

**Comment by zzz6519003** [comment]
sure, also category by theme

**Comment by RichardLitt** [comment]
> Should each year of a conference be treated as a distinct entity? 

Nah. If it was awesome once, it should be awesome in the future. Maybe let's just stop archiving awesome conferences that happened, and only look to ones that are going to repeat? Perhaps an age limit would help - if two or more years ago, then remove it. 

> Should we be proactive about moving conferences that have passed from the top to the Past Conferences section? 

See above. 

@zzz6519003 and @thejessleigh happy to make anyone a contrib. let me know.

**Comment by dlondero** [comment]
Any help needed? Are you still willing to keep this going?

**Comment by RichardLitt** [comment]
Help would be great. I am not actively sourcing conferences at the moment.
