### ISSUE TITLE
Quick note for each conference

### ISSUE THREAD

**Issue by sjfricke** [RichardLitt/awesome-conferences#107]
As someone who is looking for awesome conferences, I feel it's impractical to start ctrl-clicking all of them to quick see "what kind of conference is it" 

Why not add a small 1-3 word category next to it since I am pretty sure most people are going to check this list out for a conference they **don't** know about. This is due to the fact some names are more descriptive of the conference then others

so for example

* [DEFCON](https://defcon.org/) // [@_defcon_](https://twitter.com/_defcon_)
* [DinosaurJS](http://dinosaurjs.org/) // [@dinosaur_js](https://twitter.com/dinosaur_js)

It would look like

* [DEFCON](https://defcon.org/) - Security // [@_defcon_](https://twitter.com/_defcon_)
* [DinosaurJS](http://dinosaurjs.org/) - JavaScript // [@dinosaur_js](https://twitter.com/dinosaur_js)

**Comment by RichardLitt** [comment]
I agree with you. I've merged a long-standing PR, and adding a Pull Request template. Want to help me move some conferences from the old format to the new one? 

Closing this, for now, as actionably there's nothing to do. Let's track this move in #3.

**Comment by sjfricke** [comment]
@RichardLitt  I would be happy to help, I am currently running the [awesome-webgl](https://github.com/sjfricke/awesome-webgl) page and wouldn't mind spending some time reformating awesome-conferences

is there a branch or project set up for the new format?

**Comment by RichardLitt** [comment]
\o/ Awesome. 

No branch set up - this is going to be a long process. I'd suggest moving lines out of `old conferences` and into `conferences`, adopting the new format, and then just make a PR for however many you do in any given chunk. That way, we don't end up with long standing PRs, and it's easier to review code as it comes in. There's no system to break by having old and new formats, so we can just keep chugging until it is done.
