### ISSUE TITLE
Find a way to add in notes

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-conferences#34]
For instance, this year's JSDC had these note repositories: 

https://github.com/aar0nTw/jsdc2014-notes
https://github.com/substack/jsdc.tw-2014

This should be captured, somewhere.

**Comment by simonv3** [comment]
@RichardLitt what's wrong with columns as far as UX goes?

**Comment by RichardLitt** [comment]
Should have phrased that as "I really don't like looking at grids", not "columns !== good UX". I find grids instantly alienating, hard to look up what you're trying to find, and difficult to parse immediately. Might just be me, though.

**Comment by RichardLitt** [comment]
Done now. Added in JSDC notes to https://github.com/RichardLitt/awesome-conferences/pull/108.
