### ISSUE TITLE
Add in http://jsconf.com/

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-conferences#44]

**Comment by Stephn-R** [comment]
What is this for specifically? Dynamic updating of the list via jsconf.com?

**Comment by RichardLitt** [comment]
This is a reminder to look through these conferences. All of the JS family of conferences are pretty awesome, afaik - the community really cares about code of conduct and lowering barriers to entry. I didn't have the time to add these when I saw this site, but hopefully someone (maybe me, later) can go through and list the conferences there here.

**Comment by Stephn-R** [comment]
Got it. I will look into this in the morning

**Comment by RichardLitt** [comment]
:palm_tree:
