### ISSUE TITLE
Would anyone like to help with Chinese conferences?

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-conferences#45]
I think this would be good: http://gopherchina.org/

But I really have no idea. Is there a market for Chinese conferences to be recognized here, too?

**Comment by Stephn-R** [comment]
+1

perhaps we open the table up to other languages and countries too?

**Comment by RichardLitt** [comment]
We should. I'm not exactly sure how best to do this, especially as I am not fluent in any other language.
