### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arthurvr** [RichardLitt/awesome-conferences#55]
This repo seems to miss a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by RichardLitt** [comment]
Cheers. Fixed.

**Comment by Stephn-R** [comment]
What about having a LICENSE.md file?

**Comment by RichardLitt** [comment]
There's no real need; that license pretty much sums it up, and the README is just as good a place to put it.
