### ISSUE TITLE
Community Conferences Lists

### ISSUE THREAD

**Issue by denji** [RichardLitt/awesome-conferences#59]
* [ ] [Interdisciplinary Open Source Community Conferences](https://gist.github.com/maxogden/322a649ff84fe1c2a680)
* [ ] [Awesome Ruby events (meetups, conferences, camps, etc.)](https://github.com/planetruby/awesome-events)
* [ ] https://github.com/FrontenderMagazine/conference-videos
* [ ] [PHP Conferences Fall 2015](https://gist.github.com/DragonBe/51002bd40a6fa99a5123)
* [ ] [Conferences worth proposing](https://gist.github.com/dxnn/55ebf7363cc5bcc7677b)
* [ ] https://gist.github.com/elijahmanor/0bfe2697156c495daca0
* [ ] [Google Developer Groups in Ukraine](http://gdg.org.ua) ([GitHub](https://github.com/GDG-Ukraine/))
* [ ] [iOS & OSX Developers Conferences](https://github.com/Lascorbe/CocoaConferences)
* [ ] [awesome WWDC resource list for conference](https://github.com/maximveksler/awesome-wwdc)
* [ ] https://github.com/rosarior/awesome-django#conferences
* [ ] https://github.com/rosskukulinski/nodejs-conference-cfps
* [ ] [microXchg - The Microservices Conference](http://microxchg.io)
* [ ] [stack72/conference - 2014](https://github.com/stack72/conference/blob/master/2014.md#conferences-for-2014)
* [ ] [Frameworks Days](http://frameworksdays.com/)
* [ ] https://github.com/ZaiLynch/area41-2014-linklist
* [ ] [Upcoming Developer Conferences](https://github.com/MurtzaM/Developer-Conferences)
* [ ] [Web European 
Conference](http://webnextconf.eu)
* [ ] [USENIX conferences](https://www.usenix.org/conferences)
* [ ] [Monitorama](http://monitorama.com/) ([Twitter](https://twitter.com/Monitorama))
* [ ] [CGO International](http://cgo.org)
* [ ] [HiPEAC conference](https://www.hipeac.net)
* [ ] [GOTO Conferences](http://gotocon.com/) ([YouTube](https://www.youtube.com/user/GotoConferences))
* [ ] [IPC Conference](https://phpconference.com) ([YouTube](https://www.youtube.com/user/PHPcon))
* [ ] [CppCon](http://cppcon.org/) ([RSS](http://cppcon.org/feed/), [YouTube](https://www.youtube.com/user/CppCon))
* [ ] https://twitter.com/jakerella/lists/conferences/members

###### Non conferences
* ~~[front-end-collect - Chinese](https://github.com/foru17/front-end-collect)~~
* ~~https://gist.github.com/macintux/5354837~~
* ~~[list of interesting conference talks and videos on PHP](https://github.com/phptodayorg/php-must-watch)~~
* ~~[Useful list of must-watch talks about CSS](https://github.com/AllThingsSmitty/must-watch-css)~~

**Comment by RichardLitt** [comment]
@denji Why did you close this?

**Comment by RichardLitt** [comment]
I added what I thought were good lists. None of the individual conferences were added, because I'm not sure why you added them here. Happy to accept them if you change it up a bit. Thanks, @denji! Attributed you on the commits.
