### ISSUE TITLE
Include video and live stream links

### ISSUE THREAD

**Issue by fd** [RichardLitt/awesome-conferences#67]
Awesome conferences have videos and live streams.

**Comment by RichardLitt** [comment]
This is true, they do! I am down for this. Ideas on how to start?

**Comment by diasdavid** [comment]
We've created a yearbook for all LXJS ones http://yearbook.lxjs.org/ :)

**Comment by RichardLitt** [comment]
@diasdavid Is there a 2015 one??

**Comment by diasdavid** [comment]
@RichardLitt we skipped this year, unfortunately - http://lxjs.tumblr.com/post/121098329048/the-javascript-conference-of-lisbon-lxjs

**Comment by RichardLitt** [comment]
@diasdavid Would you mind PRing LXJS with the new template? If not, I'd be happy to, but I think you'd be better at it.

**Comment by Daniel-at-github** [comment]
For python conferences the video should be in https://pyvideo.org/
If you see any videos missing, let us know (https://github.com/pyvideo/data/issues)
