### ISSUE TITLE
Add Dent:Space and Abstractions.io

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/awesome-conferences#96]
Because they look awesome!

http://space.dentthefuture.com/
http://abstractions.io/

Stubbing this issue because I am focusing on other things right now.

**Comment by RichardLitt** [comment]
Pinged some people I know who went to these.

**Comment by RemyPorter** [comment]
I was an attendee of Abstractions. It was a polished, inclusive conference with a *great* speaker-list. Going through the points:

* A code of conduct that is explicitly mentioned and upheld: **It definitely had one, page 18 in the [program](https://drive.google.com/file/d/0B7mlyZ0eTfMFYVZacVhiV3R6ZUk/view). I can't speak to its enforcement, but knowing the organizers, I like to think it was. They have a similar code at their Code & Supply meetings (the org that sponsored Abstractions), and it is enforced**
* A great line up of talks : **Again, I draw your attention to the program. I think the Larry Wall talk was my favorite, just to see Vim used as a presentation tool. That's just me.**
* A recurring schedule: **This is *not* the case, and it is an explicitly "as needed" conference. I believe they are planning one for 2018, and they're sponsoring several one-track conferences over the next year.**
* Diversity; both in the talks and in the community who attend: **They did great here. Again, skim the program for the speakers, but as an attendee, I saw a wonderfully varied crowd in attendance.**
* Grants for students and minorities: **Yep. I don't know how large or how many there were, but there definitely were some.**
* Accessibility for disabled persons: wheelchair access, interpreters or captioning, etc: **They used the David L. Lawrence convention center, which is fully handicap accessible, and they provided live captioning of the larger talks.**
* Alcohol-free drink options: **I don't believe that there was any alcohol on site, period.**
* Quiet rooms and safe space. **Yes.**

I'm a huge fan of the work Code & Supply does for the Pittsburgh technology scene, and I definitely think Abstractions was an awesome conference.

**Comment by RichardLitt** [comment]
@RemyPorter That is an incredible write up! Thank you!

Would you mind adding that to a PR? If not, I am happy to do it. :)

**Comment by RemyPorter** [comment]
I can do that.

**Comment by RichardLitt** [comment]
Closed in https://github.com/RichardLitt/awesome-conferences/commit/ae7be831c23751f13eb8a21f4dd31431afaf7a83.
